### Login
POST http://localhost:8000/api/login HTTP/1.1
content-type: application/json

{
    "username": "carlos880425@gmail.com",
    "password" : "!App.123"
}

### CREAR Ingreso
POST http://localhost:8000/api/incomes HTTP/1.1
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYzRkZGQxNjY1YWJmOTA5ZGQxODhjNSIsIm5hbWUiOiJDYXJsb3MgUmV5ZXMiLCJlbWFpbCI6ImNhcmxvczg4MDQyNUBnbWFpbC5jb20iLCJpYXQiOjE2NDAyOTQxMzl9.nr0sBB9VYso6qmSR_7ukEflduYOaP5VvZCC4PUihOwk
content-type: application/json

{
    "month": 6,
    "income": 400,
    "businessId": "61c4ea58a62cbab34ec5fdda"
}

# ### LOGIN DEL USUARIO


# ### LISTAR TODOS LOS USUARIOS
# GET http://localhost:8000/api/usuarios HTTP/1.1
# x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MWE1NGY4NDVhMDJjNmFmODFmNmQxZmMiLCJlbWFpbCI6InNlcGhpdG9yMkBnbWFpbC5jb20iLCJmaXJzdG5hbWUiOiJGcmFuY2lzY28iLCJsYXN0bmFtZSI6IkJvaXNpZXIiLCJpYXQiOjE2MzgyMjM3NDgsImV4cCI6MTYzODIzMDk0OH0.1GNwZ5H5mALIbFIgWz2Ts0gLCaDq9tvnJOIovCTRLhM